### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by Pinche-Dev** [AnkushSinghGandhi/Debian-touchpad-gestures#1]
started installing gestures app
./gestures-setup.sh: line 21: cd: /home/ankush/Downloads/gestures-master/: No such file or directory
python3: can't open file 'setup.py': [Errno 2] No such file or directory

**Comment by Pinche-Dev** [comment]
Ubuntu 20...LTS

**Comment by AnkushSinghGandhi** [comment]
replace my username with your

**Comment by AnkushSinghGandhi** [comment]
here "home/ankush/Downloads/gestures-master/"
